CREATE DATABASE PROYECTO_DAUTE;
USE PROYECTO_DAUTE;
/*------------------------------------------TABLAS CATALOGO-------------------------------------*/
CREATE TABLE ROL(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(500),
    CREATE_AT DATE,
    UPDATE_AT DATE
);
CREATE TABLE CATEGORIA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(250),
    CREATE_AT DATE,
    UPDATE_AT DATE
);
CREATE TABLE DEPARTAMENTOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(250),
    CREATE_AT DATE,
    UPDATE_AT DATE
);
CREATE TABLE METODO_PAGO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(250),
    CREATE_AT DATE,
    UPDATE_AT DATE
);
CREATE TABLE PRODUCTOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(500),
    DESCRIPCION VARCHAR(2500),					/*breve descripcion del producto registrado*/
    PRECIO DOUBLE,
    ESTADO INT, 								/*Define la disponibilidad del producto*/
    VECES_VENDIDO INT,
    STOK INT, 									/*Cantidad de producto en bodega*/
    FOTO VARCHAR(5000),
	CREATE_AT DATE,
    UPDATE_AT DATE,
    CATEGORIA_ID INT,
    
    FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);
CREATE TABLE USUARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NICKNAME VARCHAR(500),
    FOTO VARCHAR(1500),
    EMAIL VARCHAR(500),
    PASS VARCHAR(500),	
    ROL_ID INT,
    TIPO_SUSCRIPCION INT,                        /*SUSCRIPCION ESTANDAR 0 PREMIUN 1*/
    GENERO VARCHAR(100),
    CREATEA_AT DATE,
    UPDATE_AT DATE,
    
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID)
);
CREATE TABLE DIRECCION(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID INT,
    DEPARTAMENTO_ID INT,
    MUNICIPIO VARCHAR(1500),
    CALLE VARCHAR(1500),
    LUGAR_REFERENCIAS VARCHAR(1500),				/*LUGAR DE REFERENCIA DONDE SE ENTREGARA EL PEDIDO O ESTA SU LOCAL*/
    TELEFONO VARCHAR(250),
    TELEFONO_EXTRA VARCHAR(250),
    
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(ID)
);
/*------------------------------------------------TABLAS OPERACIONES PARA FUNCION DEL SISTEMA---------------------------------------------*/

CREATE TABLE CARRITO_DE_COMPRAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT,
    ID_USUARIO INT,
    PRECIO DOUBLE,
    DESCUENTO DOUBLE,
    ESTADO_VENTA INT, 									/*ESTADO VENTA PROCESADA 0 VENTA REALIZADA 1*/
    
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);
CREATE TABLE ORDENES(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_DIRECCION INT,
    ID_METODO_PAGO INT,
    FECHA DATE,
    SUB_TOTAL DOUBLE,
    TOTAL DOUBLE,
    
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID)
);
CREATE TABLE DETALLE_COMPRA(
	ID_ORDEN INT,
    ID_PRODUCTO INT,
    DESCUENTO DOUBLE,
    PRECIO DOUBLE,
	FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
    
);

INSERT INTO ROL VALUES (NULL,"USUARIO",CURDATE(),curdate());
INSERT INTO ROL VALUES (NULL,"EMPLEADO",CURDATE(),curdate());
INSERT INTO ROL VALUES (NULL,"ADMINISTRADOR",CURDATE(),curdate());

INSERT INTO CATEGORIA VALUES (NULL,"MUEBLES",CURDATE(),curdate());
INSERT INTO CATEGORIA VALUES (NULL,"DECORACION",CURDATE(),curdate());
INSERT INTO CATEGORIA VALUES (NULL,"BEBIDAS",CURDATE(),curdate());

INSERT INTO METODO_PAGO VALUES (NULL,"VISA",CURDATE(),curdate());
INSERT INTO METODO_PAGO VALUES (NULL,"PAYPAL",CURDATE(),curdate());
INSERT INTO METODO_PAGO VALUES (NULL,"BITCOIN",CURDATE(),curdate());

INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('AHUACHAPAN');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('CABAÑAS');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('CHALATENANGO');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('CUCATLAN');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('LA LIBERTAD');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('LA PAZ');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('LA UNION');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('MORAZAN');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('SAN MIGUEL');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('SAN SALVADOR');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('SAN VICENTE');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('SANTA ANA');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('SONSONATE');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('USULUTAN');